'use client';

import { useState } from 'react';

const CATEGORIES = ['All', 'Fantasy', 'Sci-Fi', 'Nature', 'Architecture', 'Portrait'];

const galleryItems = [
  { id: 1, title: 'Cyberpunk City', category: 'Sci-Fi', seed: 101, prompt: 'Futuristic cyberpunk city with neon lights at night' },
  { id: 2, title: 'Mountain Temple', category: 'Nature', seed: 202, prompt: 'Ancient temple on mountain peak with clouds' },
  { id: 3, title: 'Dragon Knight', category: 'Fantasy', seed: 303, prompt: 'Epic fantasy warrior on dragon in storm' },
  { id: 4, title: 'Glass Building', category: 'Architecture', seed: 404, prompt: 'Modern glass skyscraper reflecting sky' },
  { id: 5, title: 'Neon Portrait', category: 'Portrait', seed: 505, prompt: 'Portrait with neon lighting and shadows' },
  { id: 6, title: 'Space Station', category: 'Sci-Fi', seed: 606, prompt: 'Massive space station orbiting Earth' },
  { id: 7, title: 'Cherry Blossoms', category: 'Nature', seed: 707, prompt: 'Japanese garden with cherry blossoms' },
  { id: 8, title: 'Mech Warrior', category: 'Sci-Fi', seed: 808, prompt: 'Giant mech robot in destroyed city' },
  { id: 9, title: 'Floating Islands', category: 'Fantasy', seed: 909, prompt: 'Fantasy floating islands in the sky' },
  { id: 10, title: 'Minimal Interior', category: 'Architecture', seed: 1010, prompt: 'Minimalist white interior design' },
  { id: 11, title: 'Forest Spirit', category: 'Fantasy', seed: 1111, prompt: 'Spirit creature in enchanted forest' },
  { id: 12, title: 'Ocean City', category: 'Sci-Fi', seed: 1212, prompt: 'Underwater city with bioluminescent creatures' },
];

export default function Gallery() {
  const [activeCategory, setActiveCategory] = useState('All');
  const [selectedImage, setSelectedImage] = useState<typeof galleryItems[0] | null>(null);

  const filteredItems = activeCategory === 'All'
    ? galleryItems
    : galleryItems.filter(item => item.category === activeCategory);

  return (
    <section className="gallery-section" id="gallery">
      <div className="container">
        <div className="section-header">
          <span className="section-badge">🖼️ Gallery</span>
          <h2 className="section-title">Created by Our Community</h2>
          <p className="section-subtitle">
            Explore millions of stunning images generated by AI Studio users
          </p>
        </div>

        {/* Category Filter */}
        <div style={{ display: 'flex', justifyContent: 'center', gap: '0.5rem', marginBottom: '3rem', flexWrap: 'wrap' }}>
          {CATEGORIES.map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              style={{
                padding: '0.5rem 1rem',
                borderRadius: '9999px',
                border: 'none',
                cursor: 'pointer',
                fontSize: '0.875rem',
                fontWeight: 500,
                background: activeCategory === cat ? 'var(--vercel-black)' : 'var(--vercel-white)',
                color: activeCategory === cat ? 'var(--vercel-white)' : 'var(--vercel-gray-600)',
                boxShadow: activeCategory === cat ? 'none' : '0 1px 2px rgba(0,0,0,0.1)',
                transition: 'all 0.2s'
              }}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Gallery Grid */}
        <div className="gallery-grid">
          {filteredItems.map((item) => (
            <div
              key={item.id}
              className="gallery-item"
              onClick={() => setSelectedImage(item)}
            >
              <img
                src={`https://picsum.photos/seed/${item.seed}/600/600`}
                alt={item.title}
                loading="lazy"
              />
              <div className="gallery-item-overlay">
                <div>
                  <p style={{ fontWeight: 600, color: '#fff', marginBottom: '0.25rem' }}>{item.title}</p>
                  <p style={{ fontSize: '0.75rem', color: 'rgba(255,255,255,0.8)' }}>
                    {item.prompt.substring(0, 40)}...
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Lightbox Modal */}
      {selectedImage && (
        <div
          onClick={() => setSelectedImage(null)}
          style={{
            position: 'fixed',
            inset: 0,
            background: 'rgba(0, 0, 0, 0.9)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1000,
            padding: '2rem',
            cursor: 'pointer',
          }}
        >
          <div
            onClick={(e) => e.stopPropagation()}
            style={{
              maxWidth: '700px',
              width: '100%',
              background: 'var(--vercel-black)',
              borderRadius: '16px',
              overflow: 'hidden',
            }}
          >
            <img
              src={`https://picsum.photos/seed/${selectedImage.seed}/800/800`}
              alt={selectedImage.title}
              style={{ width: '100%', display: 'block' }}
            />
            <div style={{ padding: '1.5rem' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <div>
                  <h3 style={{ fontSize: '1.25rem', fontWeight: 600, color: '#fff', marginBottom: '0.5rem' }}>
                    {selectedImage.title}
                  </h3>
                  <p style={{ color: 'var(--vercel-gray-400)', fontSize: '0.875rem' }}>
                    {selectedImage.prompt}
                  </p>
                </div>
                <span style={{
                  padding: '0.25rem 0.75rem',
                  background: 'var(--vercel-gray-800)',
                  borderRadius: '9999px',
                  fontSize: '0.75rem',
                  color: 'var(--vercel-gray-400)'
                }}>
                  {selectedImage.category}
                </span>
              </div>
              <div style={{ display: 'flex', gap: '0.75rem', marginTop: '1.5rem' }}>
                <button
                  onClick={() => setSelectedImage(null)}
                  className="btn btn-secondary"
                  style={{ flex: 1 }}
                >
                  Close
                </button>
                <button
                  className="btn btn-primary"
                  style={{ flex: 1 }}
                  onClick={() => {
                    // Navigate to remix page
                    window.location.href = '/generate/remix';
                  }}
                >
                  Remix This
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </section>
  );
}
